### ISSUE TITLE
error: missing / (unclosed regex)

### ISSUE THREAD

**Issue by garyrob** [SimonDegraeve/react-coffee-quickstart#2]
Hello, I downloaded the project on OS X and did
  sudo npm install
and then
  npm run start

I got the following error:

```
Starting child process with 'coffee server.coffee'
Ignoring directory '/Users/garyrob/Source/test/react-coffee-quickstart/node_modules'.
Watching directory '/Users/garyrob/Source/test/react-coffee-quickstart' for changes.
Point your browser at http://localhost:3000
/Users/garyrob/Source/test/react-coffee-quickstart/client.coffee:16:29: error: missing / (unclosed regex)
      <h1>Hello, anonymous!</h1>
                            ^
/Users/garyrob/Source/test/react-coffee-quickstart/client.coffee:16:29: error: missing / (unclosed regex)
      <h1>Hello, anonymous!</h1>
                            ^
```

**Comment by datenpate** [comment]
+1

**Comment by sheldonth** [comment]
+1

**Comment by cjroth** [comment]
+1

**Comment by cjroth** [comment]
Renaming `client.coffee` to `client.cjsx` and updating the reference to it in `server.coffee` solves this, but then I get the following:

```
TypeError: Object #<Object> has no method 'createElement'
  at [object Object].React.createClass.render (/Users/chris/d/react-coffee-quickstart/client.cjsx:73:86)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/chris/d/react-coffee-quickstart/node_modules/react/lib/ReactCompositeComponent.js:1394:34)
  at [object Object]._renderValidatedComponent (/Users/chris/d/react-coffee-quickstart/node_modules/react/lib/ReactPerf.js:57:21)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/chris/d/react-coffee-quickstart/node_modules/react/lib/ReactCompositeComponent.js:947:14)
  at [object Object].mountComponent (/Users/chris/d/react-coffee-quickstart/node_modules/react/lib/ReactPerf.js:57:21)
  at /Users/chris/d/react-coffee-quickstart/node_modules/react/lib/ReactServerRendering.js:53:38
  at ReactServerRenderingTransaction.Mixin.perform (/Users/chris/d/react-coffee-quickstart/node_modules/react/lib/Transaction.js:159:20)
  at Object.renderComponentToString (/Users/chris/d/react-coffee-quickstart/node_modules/react/lib/ReactServerRendering.js:51:24)
  at /Users/chris/d/react-coffee-quickstart/node_modules/react-async/index.js:71:26
```
